Repository Codeit-sprint2-4-5/global-nomad, pull requests merged in 2024-04, with the labels that each got.

#145 feat: 체험상세 - 체험 상세 정보, 케밥 구현
  src/components/domain/activityInfo/ActivityInfo.module.scss
  src/components/domain/activityInfo/ActivityInfo.tsx
Labels: 내 체험

#155 Feat/auth/seongseon
  src/apis/auth.ts
  src/apis/axios.ts
  src/components/common/auth/Auth.tsx
  src/hooks/useIsLoggedIn.ts
  src/pages/_app.tsx
  src/types/auth.ts
Labels: 공통

#157 feat: 예약현황 페이지
  src/apis/get/getAbledResrvations.ts
  src/components/common/Modals/ModalContents/reservationInfo/ReservationInfo.module.scss
  src/components/common/Modals/ModalContents/reservationInfo/ReservationInfo.tsx
  src/components/common/chips/Chips.tsx
  src/components/domain/reservationStatus/Calendar.module.scss
  src/components/domain/reservationStatus/Calendar.tsx
  src/components/domain/reservationStatus/Days.tsx
  src/pages/mypage/[id]/index.tsx
  src/pages/reservationStatus/index.tsx
Labels: 예약

#160 feat: 검색 컴포넌트 추가 기능 구현
  src/components/common/search/Search.module.scss
  src/components/common/search/Search.tsx
Labels: 공통

#165 Feat : 체험 수정, 체험 등록 페이지 구현
  package-lock.json
  package.json
  src/apis/get/getActivity.ts
  src/apis/patch/patchActivity.ts
  src/apis/post/postActivity.ts
  src/apis/post/postActivityImageUrl.ts
  src/components/common/Input/DateInput.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/inputField.module.scss
  src/components/common/Modals/ModalContents/ReservationInfo/ReservationInfo.module.scss
  src/components/common/Modals/ModalContents/ReservationInfo/ReservationInfo.tsx
  src/components/common/Modals/ModalContents/Review/Review.tsx
  src/components/common/Modals/ModalContents/dateForm/DateForm.tsx
  src/components/common/Modals/ModalContents/dateForm/smallCalendar/SmallCalender.tsx
  src/components/common/Modals/ModalContents/utills/dateChange.ts
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/floatingBox/FloatingBox.tsx
  src/components/domain/.gitkeep
  src/components/domain/addActivity/AddActivityForm.module.scss
  src/components/domain/addActivity/AddActivityForm.tsx
  src/components/domain/addActivity/AddressInput.tsx
  src/components/domain/addActivity/ImageInput.tsx
  src/components/domain/addActivity/ImageList.tsx
  src/components/domain/addActivity/ScheduleList.module.scss
  src/components/domain/addActivity/ScheduleList.tsx
  src/components/domain/addActivity/utills/index.ts
  src/components/domain/addActivity/utills/isValidImage.ts
  src/components/domain/addActivity/utills/setUrlsId.ts
  src/pages/_document.tsx
  src/pages/addActivity/AddActivityPage.module.scss
  src/pages/addActivity/index.tsx
  src/pages/editActivity/index.tsx
Labels: bug, 수정중

#180 feat: 메인 페이지 구현
  src/apis/get/getActivities.ts
  src/components/common/cardResource/CardResource.tsx
  src/components/common/cardResource/cardResource.module.scss
  src/components/common/category/Category.module.scss
  src/components/common/dropdownMenu/DropdownMenu.module.scss
  src/components/domain/main/MainPage.module.scss
  src/components/domain/main/MainPage.tsx
  src/components/domain/main/activitiesList/ActivitiesList.module.scss
  src/components/domain/main/activitiesList/ActivitiesList.tsx
  src/components/domain/main/activitiesList/SearchActivitiesHeader.tsx
  src/components/domain/main/banner/Banner.module.scss
  src/components/domain/main/banner/Banner.tsx
  src/components/domain/main/categoryFilter/CategoryFilter.module.scss
  src/components/domain/main/categoryFilter/CategoryFilter.tsx
  src/components/domain/main/popularActivitiesList/PopularActivitiesList.module.scss
  src/components/domain/main/popularActivitiesList/PopularActivitiesList.tsx
  src/hooks/useResponsiveSize.ts
  src/pages/index.tsx
  src/stores/Activities.ts
Labels: 메인

#218 fix: 메인 페이지 및 기타 요구 사항 수정
  public/images/Image_hot_air_balloon.png
  public/images/Image_stepping_stone.jpg
  public/images/Image_street_dance.jpg
  src/components/common/GNB/GNB.module.scss
  src/components/common/GNB/GNB.tsx
  src/components/common/avatar/Avatar.module.scss
  src/components/common/cardResource/CardResource.module.scss
  src/components/common/cardResource/CardResource.tsx
  src/components/common/category/Category.module.scss
  src/components/common/filter/Filter.module.scss
  src/components/common/filter/Filter.tsx
  src/components/common/layout/Layout.module.scss
  src/components/common/layout/MainLayout.tsx
  src/components/common/menu/Menu.tsx
  src/components/common/pagination/Pagination.module.scss
  src/components/common/search/Search.tsx
  src/components/common/skeleton/Skeleton.module.scss
  src/components/common/skeleton/Skeleton.tsx
  src/components/domain/main/MainPage.module.scss
  src/components/domain/main/MainPage.tsx
  src/components/domain/main/activitiesList/ActivitiesList.module.scss
  src/components/domain/main/activitiesList/ActivitiesList.tsx
  src/components/domain/main/banner/Banner.tsx
  src/components/domain/main/categoryFilter/CategoryFilter.module.scss
  src/components/domain/main/categoryFilter/CategoryFilter.tsx
  src/components/domain/main/popularActivitiesList/PopularActivitiesList.module.scss
  src/components/domain/main/popularActivitiesList/PopularActivitiesList.tsx
  src/components/domain/main/postActivity/PostActivityButton.module.scss
  src/components/domain/main/postActivity/PostActivityButton.tsx
  src/components/domain/mypage/myReservations/MyReservations.tsx
  src/constants/importImages.ts
  src/hooks/useResponsiveSize.ts
Labels: 메인
