Repository Codeit-sprint2-4-5/global-nomad, pull requests merged in 2024-03, with the labels that each got.

#2 feat: ImportImage ,ICON 객체화 아이콘 추가
  public/icons/Icon_X.svg
  public/icons/Icon_X_bold.svg
  public/icons/Icon_X_medium.svg
  public/icons/Icon_cancel.svg
  public/icons/Icon_left-arrow_active.svg
  public/icons/Icon_left-arrow_default.svg
  public/icons/Icon_left-arrow_variant1.svg
  public/icons/Icon_plus.svg
  public/icons/Icon_plus_time.svg
  public/icons/Icon_right-arrow_active.svg
  public/icons/Icon_right-arrow_default.svg
  public/icons/Icon_right-arrow_variant1.svg
  src/constants/importImages.ts
  src/constants/index.ts
Labels: 공통

#8 style - 누락된 Icon 추가
  public/icons/Icon_minus_time.svg
Labels: 공통

#17 Style: main.scss Import 문 추가 _motion
  src/styles/main.scss
Labels: 공통

#6 feat: footer UI 구현 SNS링크 기능구현
  src/components/common/footer/Footer.tsx
  src/components/common/footer/footer.module.scss
Labels: 공통

#15 faet: 예약 태그 구현
  src/components/common/.gitkeep
  src/components/common/ReservationTag/ReservationTag.module.scss
  src/components/common/ReservationTag/index.tsx
Labels: 공통, 예약

#23 feat: Chips 컴포넌트 구현
  src/components/common/chips/Chips.module.scss
  src/components/common/chips/Chips.tsx
Labels: 공통

#24 feat: search 컴포넌트 구현
  src/components/common/search/Search.module.scss
  src/components/common/search/Search.tsx
Labels: 공통

#38 Feat: Input 컴포넌트 추가
  .gitignore
  src/components/common/Input/Input.tsx
  src/components/common/Input/inputField.module.scss
  src/constants/index.ts
  src/constants/inputFieldValidation.ts
  src/hooks/index.ts
  src/hooks/useToggleButton.ts
Labels: 공통

#54 style: button 사이즈의 height값 대신 padding 으로 대체
  src/components/common/button/Buttons.module.scss
Labels: 공통

#56 Refactor: 버튼들 onClick 타입명시 및 transition 수정
  src/components/common/button/BaseButton.tsx
  src/components/common/button/Buttons.module.scss
  src/components/common/button/IconButton.tsx
  src/components/common/button/MixButton.tsx
Labels: 공통

#46 design: layout 추가
  src/components/common/layout/Layout.module.scss
  src/components/common/layout/Layout.tsx
Labels: 공통

#57 Feat: InputField input과 textarea 분리 Textarea 컴포넌트 구현
  src/components/common/Input/Input.tsx
  src/components/common/Input/Textarea.tsx
  src/components/common/Input/inputField.module.scss
Labels: 공통

#28 feat: popup 컴포넌트 구현
  src/components/common/popup/confirm/Confirm.module.scss
  src/components/common/popup/confirm/Confirm.tsx
  src/components/common/popup/question/Question.module.scss
  src/components/common/popup/question/Question.tsx
Labels: 공통

#41 feat: CardResource 컴포넌트 구현
  next.config.mjs
  pull_request_template.md
  src/components/common/cardResource/CardResource.tsx
  src/components/common/cardResource/cardResource.module.scss
  src/components/common/footer/footer.module.scss
  src/types/activities.ts
Labels: 공통

#32 Feat: sideNavMenu 기본 UI 구현
  src/components/sideNavMenu/SideNavMenu.tsx
  src/components/sideNavMenu/sideNavMenu.module.scss
  src/constants/menuItems.ts
Labels: 공통

#42 feat: 페이지네이션 구현
  src/components/common/pagination/Pagination.module.scss
  src/components/common/pagination/Pagination.tsx
Labels: 공통

#45 Feat: dropdown 컴포넌트 구현
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/dropdown/dropdown.module.scss
  src/constants/inputFieldValidation.ts
  src/hooks/index.ts
  src/hooks/useOutsideClose.ts
Labels: 공통

#78 feat: 공통 - 타이틀 컴포넌트 구현
  src/components/common/title/Title.module.scss
  src/components/common/title/Title.tsx
Labels: 공통

#72 feat: 예약현황 - 달력 컴포넌트 구현
  src/components/calendar/Calendar.module.scss
  src/components/calendar/Calendar.tsx
Labels: 예약

#91 refactor: Chips 상태 확정 -> 승인 변경
  src/components/common/chips/Chips.tsx
Labels: 공통

#85 Feat: signup, signin page 구현
  src/apis/auth.ts
  src/components/auth/formHeader/FormHeader.module.scss
  src/components/auth/formHeader/FormHeader.tsx
  src/components/auth/signin/AuthForm.module.scss
  src/components/auth/signin/AuthForm.tsx
  src/components/auth/signup/AuthForm.module.scss
  src/components/auth/signup/AuthForm.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Input/inputField.module.scss
  src/components/common/button/BaseButton.tsx
  src/components/common/button/Buttons.module.scss
  src/constants/inputFieldValidation.ts
  src/hooks/index.ts
  src/hooks/useOutsideClick.ts
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/types/auth.ts
Labels: 로그인, 회원가입

#102 Style: Menu 컴포넌트 CSS 피드백 반영
  src/components/common/category/Category.module.scss
  src/components/common/category/Category.tsx
  src/components/common/dropdownMenu/DropdownMenu.module.scss
  src/components/common/filter/Filter.module.scss
  src/components/common/menu/Menu.module.scss
Labels: 공통

#103 Feat/popup/mijin0928
  src/components/common/popup/question/Question.tsx
Labels: 공통

#112 feat: 데이터 없음 컴포넌트
  src/components/common/noDataMessgae/NoDataMessage.module.scss
  src/components/common/noDataMessgae/NoDataMessage.tsx
Labels: 공통

#114 Feat : 모달 구현
  next.config.mjs
  package-lock.json
  package.json
  src/apis/axios.ts
  src/apis/delete/deleteNotification.ts
  src/apis/get/getAbledResrvations.ts
  src/apis/get/getMyNotifications.ts
  src/apis/patch/patchReservationStatus.ts
  src/apis/post/postReservation.ts
  src/apis/post/postReview.ts
  src/apis/quertKey.ts
  src/components/common/Modals/Modal.module.scss
  src/components/common/Modals/ModalContents/ModalContents.module.scss
  src/components/common/Modals/ModalContents/dateForm/DateForm.module.scss
  src/components/common/Modals/ModalContents/dateForm/DateForm.tsx
  src/components/common/Modals/ModalContents/dateForm/smallCalendar/SmallCalender.tsx
  src/components/common/Modals/ModalContents/dateForm/smallCalendar/smallCalender.module.scss
  src/components/common/Modals/ModalContents/notifications/Notifications.module.scss
  src/components/common/Modals/ModalContents/notifications/Notifications.tsx
  src/components/common/Modals/ModalContents/reservationInfo/ReservationCard.tsx
  src/components/common/Modals/ModalContents/reservationInfo/ReservationInfo.module.scss
  src/components/common/Modals/ModalContents/reservationInfo/ReservationInfo.tsx
  src/components/common/Modals/ModalContents/review/RatingInput.tsx
  src/components/common/Modals/ModalContents/review/Review.tsx
  src/components/common/Modals/ModalContents/review/ReviewForm.tsx
  src/components/common/Modals/ModalContents/utills/dateChange.ts
  src/components/common/Modals/ModalContents/utills/getTimeAgo.ts
  src/components/common/Modals/ModalContents/utills/index.ts
  src/components/common/Modals/index.tsx
  src/components/common/ReservationTag/ReservationTag.module.scss
  src/components/common/ReservationTag/index.tsx
  src/components/common/dropdown/Dropdown.tsx
  src/components/common/floatingBox/CountMemberInput.module.scss
  src/components/common/floatingBox/CountMemberInput.tsx
  src/components/common/floatingBox/FloatingBox.module.scss
  src/components/common/floatingBox/FloatingBox.tsx
  src/constants/index.ts
  src/constants/modalType.ts
  src/pages/index.tsx
  src/types/.gitkeep
  src/types/dateform.ts
  src/types/index.ts
  src/types/reservationInfo.ts
Labels: 공통

#104 Feat: GNB 컴포넌트 구현
  src/components/common/GNB/GNB.module.scss
  src/components/common/GNB/GNB.tsx
  src/components/common/avatar/Avatar.module.scss
  src/components/common/avatar/Avatar.tsx
  src/components/common/layout/Layout.tsx
  src/types/myInfo.ts
Labels: 공통

#123 Feat: mypage-myinfo 페이지 적용
  src/apis/auth.ts
  src/components/common/Input/Textarea.tsx
  src/components/common/button/BaseButton.tsx
  src/components/common/button/Buttons.module.scss
  src/components/common/sideNavMenu/SideNavMenu.tsx
  src/components/common/sideNavMenu/sideNavMenu.module.scss
  src/components/domain/account/Account.tsx
  src/components/domain/account/form/AccountForm.module.scss
  src/components/domain/account/form/AccountForm.tsx
  src/components/domain/auth/formHeader/FormHeader.module.scss
  src/components/domain/auth/formHeader/FormHeader.tsx
  src/components/domain/auth/signin/AuthForm.module.scss
  src/components/domain/auth/signin/AuthForm.tsx
  src/components/domain/auth/signup/AuthForm.module.scss
  src/components/domain/auth/signup/AuthForm.tsx
  src/function/throttle.ts
  src/pages/mypage/[id]/Mypage.module.scss
  src/pages/mypage/[id]/index.tsx
  src/pages/mypage/index.tsx
  src/pages/signin/index.tsx
  src/pages/signup/index.tsx
  src/stores/useRoute.ts
  src/types/auth.ts
Labels: 내 정보

#148 fix: isLoading 으로 Loading이 기존 요소들을 배제함 주석처리
  src/pages/signin/index.tsx
Labels: 로그인

#121 feat: 로딩바, 스켈레톤 구현
  package-lock.json
  package.json
  src/components/common/skeleton/Skeleton.module.scss
  src/components/common/skeleton/Skeleton.tsx
  src/pages/_app.tsx
  src/pages/index.tsx
Labels: 공통
